/* eslint-disable */
export const levels =[
	[
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                           o                                                                                x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                                                                                                            x',
		'x                                                                                           x                                                                      x         x',
		'x                                                o         o                                                                                                      xx     o   x',
		'x                      o                                        xxxxx     xxxx    o                                                                              xxx     o   x',
		'x                                           x    x        xxx   |                                                                                               xxxx     o   x',
		'x                o   xxxxx             x    x                x                   xx     x   x   x         x    x            x    x           x    x            xxxxx     o   x',
		'x                                 x    x    x                     |                                      xx    xx          xx    xx         xx    xx          xxxxxx     o   x',
		'x                            x    x    x    x                                                           xxx    xxx        xxx    xxx       xxx    xxx        xxxxxxx     o   x',
		'x  @                         x    x =  x=  =x                       |                                  xxxx    xxxx   =  xxxx    xxxx =   xxxx    xxxx  =   xxxxxxxx        !x',
		'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
		'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
		'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
		'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	],

];

export const test = [
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x   @                                              x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x                                                  x   ',
	'  x           o              o             o         x   ',
	'  x                                                  x   ',
	'  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x     x   ',
	'                                               x  o  x   ',
	'                                               x!   !x   ',
	'                                               xxxxxxx   ',
];
/* eslint-enable */